//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class alınandersler
    {
        public int Id { get; set; }
        public Nullable<int> ogrNo { get; set; }
        public Nullable<int> ders_kodu { get; set; }
    
        public virtual ogrenci ogrenci { get; set; }
        public virtual der der { get; set; }
    }
}
