//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class der
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public der()
        {
            this.alınandersler = new HashSet<alınandersler>();
            this.devamsizliks = new HashSet<devamsizlik>();
            this.nots = new HashSet<not>();
        }
    
        public int ders_kodu { get; set; }
        public string ders_adi { get; set; }
        public Nullable<int> kredi { get; set; }
        public Nullable<int> sinif { get; set; }
        public Nullable<int> egitmen_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alınandersler> alınandersler { get; set; }
        public virtual egitman egitman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<devamsizlik> devamsizliks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<not> nots { get; set; }
    }
}
