//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class egitman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public egitman()
        {
            this.ders = new HashSet<der>();
        }
    
        public int Id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<int> egitmen_kodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<der> ders { get; set; }
    }
}
