//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ogrenciBilgiSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int Id { get; set; }
        public string ogrenci_sifre { get; set; }
        public string egitmen_sifre { get; set; }
        public Nullable<int> ogrenci_no { get; set; }
        public Nullable<int> egitmen_kod { get; set; }
    }
}
